// Barrel for fractal-midi/fm9.
//
// **Status: 🟡 catalog stage.** Foundation hardware-verified
// 2026-06-06 (model byte 0x12, preset switch with bank in CC0, scene
// switch 0x0C, QUERY PATCH NAME 0x0D, STATUS DUMP 0x13 — see
// `setParam.ts`). Block roster + param catalog mined from FM9-Edit's
// BinaryData XML (`blockTypes.ts` / `params.ts`, generated by
// `scripts/_research/generate-fm9-params.ts`); paramId addressing is
// III-shared and unverified-on-FM9 until calibration. The fn=0x01
// parameter SET/GET builders are cloned from the III: SET is gated
// (calibration pending), GET is a read-only family-shared hypothesis.

// Data — block roster (FM9-Edit-mined) + param catalog (III-shared
// addressing + FM9-Edit display labels).
export {
  FM9_BLOCKS,
  resolveBlock,
  resolveBlockByEffectId,
  resolveEffectId,
} from './blockTypes.js';
export type { FM9Block, ConfidenceTag } from './blockTypes.js';
export {
  FM9_FAMILIES,
  PARAMS,
  PARAMS_BY_FAMILY,
  PARAM_BY_KEY,
  FM9_DISPLAY_LABELS,
  FM9_UI_PARAM_NAMES,
  FM9_UNRESOLVED_PARAMS,
} from './params.js';
export type { Param, Unit } from './params.js';

export {
  FM9_MODEL_ID,
  FN_PARAMETER_SETGET,
  FN_SET_GET_SCENE,
  FN_QUERY_PATCH_NAME,
  FN_QUERY_SCENE_NAME,
  FN_STATUS_DUMP,
  FN_MULTIPURPOSE_RESPONSE,
  QUERY_SENTINEL,
  buildEnvelopeWithModel,
  packValue16,
  unpackValue16,
  buildSetParameter,
  buildGetParameter,
  isSetGetParameterResponse,
  parseSetGetParameterResponse,
  buildDeviceInquiry,
  isDeviceInquiryResponse,
  parseDeviceInquiryResponse,
  parseFractalFrame,
  buildSwitchPresetPC,
  buildSetScene,
  buildGetScene,
  buildQueryPatchName,
  buildStatusDump,
  isSetGetSceneResponse,
  isQueryPatchNameResponse,
  isStatusDumpResponse,
  isMultipurposeResponse,
  parseSceneResponse,
  parseQueryPatchNameResponse,
  parseMultipurposeResponse,
  describeMultipurposeResultCode,
  parseStatusDumpResponse,
} from './setParam.js';
export type { StatusDumpEntry, FM9ParameterFrameKind } from './setParam.js';
