#!/usr/bin/env tsx
/**
 * One-shot bake script — reads `samples/hydrasynth/init-patch.patch`
 * (a 2786-byte payload extracted from ASM Hydrasynth Manager's bundled
 * `Single INIT Bank.hydra` factory file), prepends the 4-byte SysEx
 * routing header `[0x06, 0x00, 0x00, 0x00]` ("Save to RAM, Bank A,
 * Patch 1"), and writes
 * `src/asm/hydrasynth-explorer/initPatchBuffer.ts` containing the
 * resulting 2790-byte wire buffer inlined as a `Uint8Array.from([...])`
 * literal.
 *
 * Run once after the .patch file changes; the generated .ts file is
 * checked in so distribution doesn't need this script at runtime.
 *
 * Usage:
 *   npx tsx scripts/hydrasynth/bake-init-patch.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..', '..');
const SOURCE = resolve(ROOT, 'samples', 'hydrasynth', 'init-patch.patch');
const TARGET = resolve(ROOT, 'packages', 'hydrasynth', 'src', 'initPatchBuffer.ts');

const PATCH_BUFFER_SIZE = 2790;
const FILE_PAYLOAD_SIZE = 2786;
const ROUTING_HEADER = [0x06, 0x00, 0x00, 0x00] as const;

const fileBytes = new Uint8Array(readFileSync(SOURCE));
if (fileBytes.length !== FILE_PAYLOAD_SIZE) {
  throw new Error(
    `expected ${FILE_PAYLOAD_SIZE}-byte .patch file at ${SOURCE}, got ${fileBytes.length} bytes`,
  );
}

const buffer = new Uint8Array(PATCH_BUFFER_SIZE);
buffer[0] = ROUTING_HEADER[0];
buffer[1] = ROUTING_HEADER[1];
buffer[2] = ROUTING_HEADER[2];
buffer[3] = ROUTING_HEADER[3];
buffer.set(fileBytes, 4);

const ROW_WIDTH = 16;
const lines: string[] = [];
for (let i = 0; i < buffer.length; i += ROW_WIDTH) {
  const row = Array.from(buffer.subarray(i, i + ROW_WIDTH))
    .map((b) => `0x${b.toString(16).padStart(2, '0')}`)
    .join(', ');
  const isLast = i + ROW_WIDTH >= buffer.length;
  lines.push(`  ${row}${isLast ? '' : ','}`);
}

const output = `/**
 * Audible-by-construction INIT patch buffer for the Hydrasynth Explorer.
 *
 * Generated by \`scripts/hydrasynth/bake-init-patch.ts\`. Do not edit by hand.
 *
 * Source: \`samples/hydrasynth/init-patch.patch\` (2786-byte payload from
 * ASM Hydrasynth Manager's \`Single INIT Bank.hydra\` bundled factory file)
 * with the 4-byte SysEx routing header \`[0x06, 0x00, 0x00, 0x00]\`
 * prepended to convert the \`.patch\` file format into the device's wire
 * buffer layout.
 *
 * The header bytes mean "Save to Bank A, Patch 1" — but
 * \`hydra_apply_init\` skips the SysEx Write Request, so the device
 * loads the patch into RAM only. No flash slot is clobbered.
 *
 * For \`apply_patch\` to a specific slot, callers override bytes
 * 2..3 (bank/patch) before sending and DO send the Write Request.
 *
 * Size is verified by \`scripts/hydrasynth/verify-init-buffer.ts\`. No
 * import from \`patchEncoder.ts\` here — patchEncoder imports this file
 * to power \`defaultPatchBuffer()\`, and a back-import would create a
 * circular load order.
 */

/** 2790-byte Hydrasynth INIT patch in wire format (4-byte header + 2786-byte payload). */
export const INIT_PATCH_BUFFER: Uint8Array = Uint8Array.from([
${lines.join('\n')}
]);
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${TARGET} (${buffer.length} bytes baked).`);
