/**
 * Produce a comprehensive markdown coverage report:
 *   - AM4 block family
 *   - For each block: list of paramIds with their Fractal symbolic name
 *   - Mark each: ✓ decoded in params.ts | △ in UI XML but not decoded |
 *               ○ not in UI XML (likely modifier/internal)
 *
 * Founder uses this as a roadmap to expand params.ts deliberately —
 * one block at a time, focusing on UI-referenced params first.
 *
 * Output: samples/captured/decoded/am4-coverage-report.md
 */

import { readFileSync, writeFileSync } from 'node:fs';

const GHIDRA_AM4 = 'samples/captured/decoded/ghidra-am4-paramnames.json';
const PARAMS_TS = 'packages/am4/src/params.ts';
const XML_REG = 'samples/captured/decoded/binarydata/extracted/__block_layout.xml';
const XML_EXPERT = 'samples/captured/decoded/binarydata/extracted/__block_layout_expert.xml';
const OUTPUT = 'samples/captured/decoded/am4-coverage-report.md';

// Load AM4-Edit XMLs to identify UI-referenced params.
function loadUI(path: string): Set<string> {
  const xml = readFileSync(path, 'utf-8');
  const set = new Set<string>();
  for (const m of xml.matchAll(/parameterName="([A-Z][A-Z0-9_]+)"/g)) set.add(m[1]);
  return set;
}
const ui = new Set([...loadUI(XML_REG), ...loadUI(XML_EXPERT)]);

// Load Ghidra catalog.
const catalog = JSON.parse(readFileSync(GHIDRA_AM4, 'utf-8'));

// Load existing params.ts (set of (block, pidHigh) we've decoded).
const paramsTs = readFileSync(PARAMS_TS, 'utf-8');
const decoded = new Set<string>();
const entryRe = /block:\s*'([a-z]+)',\s*name:\s*'[a-z0-9_]+',[\s\S]*?pidLow:\s*0x[0-9a-fA-F]+,\s*pidHigh:\s*0x([0-9a-fA-F]+)/g;
for (const m of paramsTs.matchAll(entryRe)) {
  decoded.add(`${m[1]}:${parseInt(m[2], 16)}`);
}

// Family → list of AM4 block tags. (Same map as the generator.)
const FAMILY_TO_BLOCKS: Record<string, string[]> = {
  REVERB: ['reverb'],
  DELAY: ['delay'],
  CHORUS: ['chorus'],
  FLANGER: ['flanger'],
  PHASER: ['phaser'],
  ROTARY: ['rotary'],
  TREMOLO: ['tremolo'],
  WAH: ['wah'],
  FILTER: ['filter'],
  DISTORT: ['amp', 'drive'],
  COMP: ['compressor'],
  GEQ: ['geq'],
  PEQ: ['peq'],
  GATE: ['gate'],
  ENHANCER: ['enhancer'],
  VOLUME: ['volpan'],
  CABINET: ['cab'],       // cab block, not in BLOCK_TYPE_VALUES but addressable §6k
  INPUT: ['ingate'],      // input noise gate
};

const lines: string[] = [];
const w = (s = '') => lines.push(s);

w('# AM4 parameter catalog coverage report');
w('');
w('Generated by `scripts/_research/am4-catalog-coverage-report.ts`.');
w('Source: `samples/captured/decoded/ghidra-am4-paramnames.json`');
w('(produced by `scripts/ghidra/run-am4-paramnames.cmd`).');
w('');
w('## Legend');
w('');
w('- ✓ = decoded in `packages/am4/src/params.ts`');
w('- △ = in AM4-Edit UI (`__block_layout.xml`) but not yet decoded');
w('- ○ = not in UI XML — likely modifier slot, scene-only, or internal calc state');
w('');

interface BlockSummary {
  block: string;
  family: string;
  caseIdx: number;
  catalog: { paramId: number; name: string }[];
  decoded: number;
  uiUndecoded: number;
  nonUi: number;
}
const summaries: BlockSummary[] = [];

// Per-family report
for (const eff of Object.values(catalog.effect_types) as any[]) {
  if (!eff.effectFamily) continue;
  const blocks = FAMILY_TO_BLOCKS[eff.effectFamily];
  if (!blocks) continue;
  for (const block of blocks) {
    const summary: BlockSummary = {
      block,
      family: eff.effectFamily,
      caseIdx: eff.caseIdx,
      catalog: eff.params.filter((p: any) => p.name && p.name !== '?'),
      decoded: 0,
      uiUndecoded: 0,
      nonUi: 0,
    };
    for (const p of summary.catalog) {
      if (decoded.has(`${block}:${p.paramId}`)) summary.decoded++;
      else if (ui.has(p.name)) summary.uiUndecoded++;
      else summary.nonUi++;
    }
    summaries.push(summary);
  }
}

summaries.sort((a, b) => (b.uiUndecoded + b.decoded) - (a.uiUndecoded + a.decoded));

w('## Summary');
w('');
w('| Block | Family | Case | Catalog | Decoded ✓ | UI undecoded △ | Non-UI ○ |');
w('|---|---|---|---|---|---|---|');
for (const s of summaries) {
  w(`| **${s.block}** | ${s.family} | 0x${s.caseIdx.toString(16)} | ${s.catalog.length} | ${s.decoded} | ${s.uiUndecoded} | ${s.nonUi} |`);
}
w('');
w('Plus generic params (`pidHigh` 0-9: level/mix/balance/bypass_mode) and the channel-select register (`pidHigh = 0x07D2`) which apply to every block. These are NOT shown in the per-block tables below — they\'re cross-block conventions.');
w('');

// Per-block detail
for (const s of summaries) {
  w(`## ${s.block} — pidLow per blockTypes.ts, family ${s.family} (case 0x${s.caseIdx.toString(16)})`);
  w('');
  w(`${s.catalog.length} catalog params, ${s.decoded} decoded, ${s.uiUndecoded} UI undecoded, ${s.nonUi} non-UI.`);
  w('');
  w('| Status | paramId | pidHigh | Symbolic name |');
  w('|---|---|---|---|');
  for (const p of s.catalog.sort((a, b) => a.paramId - b.paramId)) {
    const status = decoded.has(`${s.block}:${p.paramId}`) ? '✓'
                : ui.has(p.name) ? '△'
                : '○';
    const pidHigh = `0x${p.paramId.toString(16).padStart(4, '0')}`;
    w(`| ${status} | ${p.paramId} | \`${pidHigh}\` | \`${p.name}\` |`);
  }
  w('');
}

writeFileSync(OUTPUT, lines.join('\n'));
console.log(`Wrote ${lines.length} lines to ${OUTPUT}`);

// Console summary
console.log('');
console.log('Per-block summary:');
let totalDecoded = 0, totalUiUndecoded = 0, totalNonUi = 0;
for (const s of summaries) {
  totalDecoded += s.decoded;
  totalUiUndecoded += s.uiUndecoded;
  totalNonUi += s.nonUi;
  console.log(`  ${s.block.padEnd(12)} ${s.family.padEnd(10)} ${s.decoded.toString().padStart(3)}✓ / ${s.uiUndecoded.toString().padStart(3)}△ / ${s.nonUi.toString().padStart(3)}○`);
}
console.log(`  ${'TOTAL'.padEnd(12)} ${' '.repeat(10)} ${totalDecoded.toString().padStart(3)}✓ / ${totalUiUndecoded.toString().padStart(3)}△ / ${totalNonUi.toString().padStart(3)}○`);
