/**
 * Generate `packages/fractal-midi/src/gen3/axe-fx-iii/ampTypeValidParams.generated.ts`
 * from the MIT-licensed `ai-tone-assistant` community project's
 * `data/fm9/type_valid_params.json` (per-amp-model valid DISTORT param subset).
 *
 * Validates before emitting:
 *   - amp ordinals are contiguous 0..330 (aligned to the shared gen-3 amp roster);
 *   - the 4 device-true anchors (31/65/179/264) match our roster;
 *   - every param name ∈ our FM9 DISTORT catalog (clean join).
 *
 * Re-run: `npx tsx scripts/_research/gen3-amp-applicability-generate.ts`.
 * The emitted .ts is the durable committed artifact; this script is the recipe.
 */
import { writeFileSync } from 'node:fs';
import { get as httpsGet } from 'node:https';
import { FM9_PARAMS } from '../../packages/fractal-midi/src/gen3/fm9/params.js';

const RAW = 'https://raw.githubusercontent.com/wagahai850/ai-tone-assistant/main/data';

function fetchJson(url: string): Promise<unknown> {
  return new Promise((res, rej) => {
    httpsGet(url, (r) => {
      let d = '';
      r.on('data', (c) => (d += c));
      r.on('end', () => {
        try {
          res(JSON.parse(d));
        } catch (e) {
          rej(e);
        }
      });
    }).on('error', rej);
  });
}

async function main(): Promise<void> {
  const tvp = (await fetchJson(`${RAW}/fm9/type_valid_params.json`)) as {
    amp: { all_params: string[]; type_specific: Record<string, string[]> };
  };
  const eff = (await fetchJson(`${RAW}/fm9/effect_definitions.json`)) as { amp_models: string[] };

  const typeSpecific = tvp.amp.type_specific;
  const ordinals = Object.keys(typeSpecific).map(Number).sort((a, b) => a - b);

  // ── Validation gates (fail loud rather than emit a misaligned table) ──
  const contiguous = ordinals.length === 331 && ordinals[0] === 0 && ordinals[330] === 330;
  if (!contiguous) throw new Error(`amp ordinals not contiguous 0..330: ${ordinals.length} keys`);

  const anchors: Record<number, string> = { 31: 'Shiver Clean', 65: 'SV Bass 2', 179: 'Texas Star Clean', 264: 'SV Bass 1' };
  for (const [ord, name] of Object.entries(anchors)) {
    if (eff.amp_models[Number(ord)] !== name) {
      throw new Error(`anchor mismatch: amp[${ord}] = ${eff.amp_models[Number(ord)]}, expected ${name}`);
    }
  }

  const ourDistort = new Set(FM9_PARAMS.filter((p) => p.family === 'DISTORT').map((p) => p.name));
  const unknown = tvp.amp.all_params.filter((n) => !ourDistort.has(n));
  if (unknown.length > 0) throw new Error(`his param names not in our DISTORT catalog: ${unknown.join(', ')}`);

  // ── Emit ──
  const rows = ordinals.map((o) => `  [${typeSpecific[o].map((n) => `'${n}'`).join(', ')}],`).join('\n');
  const out = `/**
 * Per-amp-model VALID DISTORT-param subsets, ordinal-indexed (0..330), for the
 * shared gen-3 amp block. Index = amp read-ordinal; value = the DISTORT_* params
 * that amp model actually exposes (a tweed has no DEPTH, a modern amp does).
 *
 * Powers the gen-3 \`findCompatibleTypes\` (find_compatible_types tool +
 * apply_preset's type-knob-applicability pre-flight), so an agent is warned
 * before writing an amp knob that is inert on the selected model.
 *
 * GENERATED by scripts/_research/gen3-amp-applicability-generate.ts — DO NOT
 * hand-edit. Source: the MIT-licensed \`ai-tone-assistant\` community project
 * (data/fm9/type_valid_params.json). Cross-validated on generation: 331 ordinals
 * contiguous + aligned to our amp roster (anchors 31/65/179/264 match), every
 * param name ∈ our FM9 DISTORT catalog. The amp ordinal space is shared across
 * the gen-3 family (FM3/FM9/III); the DISTORT block is identical, so the table
 * applies family-wide.
 */
export const AMP_TYPE_VALID_PARAMS: readonly (readonly string[])[] = [
${rows}
];

/** The full set of DISTORT params any amp model may expose (union). */
export const AMP_ALL_PARAMS: readonly string[] = [
${tvp.amp.all_params.map((n) => `  '${n}',`).join('\n')}
];

/**
 * Amp read-ordinals whose valid-param set contains EVERY name in
 * \`distortParamNames\` (AND-semantics). Names must be canonical DISTORT_* form.
 * Returns ordinals in ascending order. An empty \`distortParamNames\` returns all
 * ordinals (no narrowing).
 */
export function ampOrdinalsExposingParams(distortParamNames: readonly string[]): number[] {
  const want = distortParamNames;
  const out: number[] = [];
  for (let ord = 0; ord < AMP_TYPE_VALID_PARAMS.length; ord++) {
    const have = new Set(AMP_TYPE_VALID_PARAMS[ord]);
    if (want.every((n) => have.has(n))) out.push(ord);
  }
  return out;
}
`;

  const target = 'packages/fractal-midi/src/gen3/axe-fx-iii/ampTypeValidParams.generated.ts';
  writeFileSync(target, out);
  console.log(`wrote ${target}: ${ordinals.length} amp ordinals, ${tvp.amp.all_params.length} params, all gates passed`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
