/**
 * P1 generator: emit packages/fractal-midi/src/gen3/axe-fx-iii/gen3ReadRosters.ts
 * from the validated fractal-syx-codec read-ordinal tables (Apache-2.0,
 * A. Mercurio). Run once; the emitted module is committed. Source JSON lives in
 * Drew's repo (gitignored under docs/_private), so this is a one-time import.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const DREW = 'docs/_private/fractal-syx-codec-main/fractal-syx-codec-main/data';
// Drew block file -> our gen-3 param firmware symbol (the block's Type selector).
// cab/dynacab held back (uncertain CAB_TYPE mapping, no anchor).
const BLOCK_TO_SYMBOL: [string, string][] = [
  ['amp', 'DISTORT_TYPE'],
  ['drive', 'FUZZ_TYPE'],
  ['reverb', 'REVERB_TYPE'],
  ['delay', 'DELAY_TYPE'],
  ['chorus', 'CHORUS_TYPE'],
  ['comp', 'COMP_TYPE'],
  ['flanger', 'FLANGER_TYPE'],
  ['phaser', 'PHASER_TYPE'],
  ['tremolo', 'TREMOLO_TYPE'],
  ['wah', 'WAH_TYPE'],
  ['filter', 'FILTER_TYPE'],
];

let body = '';
let total = 0;
for (const [block, symbol] of BLOCK_TO_SYMBOL) {
  const table = JSON.parse(readFileSync(`${DREW}/${block}_type_binary_ids.json`, 'utf8')) as Record<string, string>;
  const entries = Object.entries(table)
    .map(([id, name]) => [Number(id), name] as [number, string])
    .sort((a, b) => a[0] - b[0]);
  total += entries.length;
  body += `  // ${block} block type selector (${entries.length} models)\n`;
  body += `  ${symbol}: {\n`;
  for (const [id, name] of entries) {
    body += `    ${id}: ${JSON.stringify(name)},\n`;
  }
  body += `  },\n`;
}

const out = `/**
 * Gen-3 read-leg enum rosters: broadcast/read ORDINAL -> display name, for the
 * shared Axe-Fx III / FM3 / FM9 effect catalog. These name every block's Type
 * selector (amp, drive, reverb, delay, chorus, comp, flanger, phaser, tremolo,
 * wah, filter) in get_param / get_preset / list_params responses.
 *
 * READ + SET. The keys are the file-stored / broadcast ORDINAL, which IS the
 * value a gen-3 discrete SET carries as float32(ordinal) at pos 12 (sub 09 00).
 * Verified 2026-06-08 on FM3 + FM9 (file id 31 = "Shiver Clean" = the SET value).
 * There is no separate typed-SET "raw id" space and no gating: catalog.ts merges
 * this roster into each Type param's enum_values so the SAME name->ordinal drives
 * both decode (read label) and encode (set-by-name). Numeric ordinals absent from
 * a table pass through unchanged. Per-device hardware-captured overrides are
 * layered on top of this shared base by mergeGen3EnumOverrides (captured points
 * win). NOTE: the amp roster is factory-bank-correlated, so amps used in no
 * factory preset (e.g. FM9 ordinal 65 "SV Bass 2") are absent here and can only
 * be set by their numeric ordinal until a per-device override names them.
 *
 * SOURCE: fractal-syx-codec by Andrew Mercurio ("BoodieTraps"), Apache-2.0,
 * derived by correlating decoded Fractal factory presets. Independently
 * cross-validated against our own FM9 hardware read-leg captures (Texas Star
 * Clean=179, SV Bass 1=264, Blues OD=15, Blackglass 7K=36, Peaking=6); see the
 * Credits section in the repo README. cab/DynaCab held back pending a confirmed
 * CAB_TYPE mapping.
 *
 * GENERATED by scripts/_research/gen3-roster-generate.ts from the source tables.
 * Do not hand-edit; re-run the generator to refresh.
 */
export const GEN3_READ_ROSTERS: Readonly<Record<string, Readonly<Record<number, string>>>> = {
${body}};

/**
 * Deep-merge a device's hardware-captured enum overrides over the shared
 * read rosters. Device-captured points win per ordinal (hardware truth beats the
 * factory-correlated base, e.g. an FM9-specific amp at an ordinal absent from the
 * shared table). Returns the base unchanged when the device has no overrides.
 */
export function mergeGen3EnumOverrides(
  base: Readonly<Record<string, Readonly<Record<number, string>>>>,
  device?: Readonly<Record<string, Readonly<Record<number, string>>>>,
): Readonly<Record<string, Readonly<Record<number, string>>>> {
  if (device === undefined) return base;
  const out: Record<string, Record<number, string>> = {};
  for (const [sym, table] of Object.entries(base)) out[sym] = { ...table };
  for (const [sym, table] of Object.entries(device)) out[sym] = { ...(out[sym] ?? {}), ...table };
  return out;
}
`;

const target = 'packages/fractal-midi/src/gen3/axe-fx-iii/gen3ReadRosters.ts';
writeFileSync(target, out);
console.log(`Wrote ${target}: ${BLOCK_TO_SYMBOL.length} block tables, ${total} labels.`);
