/**
 * Generate `packages/fractal-midi/src/fm9/params.ts` from:
 *
 *   1. The Axe-Fx III parameter catalog (paramId addressing — the
 *      III and FM9 share the firmware param-table lineage; the III
 *      catalog is Ghidra-mined and golden-tested), and
 *   2. The FM9-Edit XML label mine
 *      (`samples/captured/decoded/fm9edit-xml-labels.json`, produced
 *      by `mine-fm9edit-xml-labels.ts`), which tells us WHICH
 *      families the FM9 exposes, the FM9-Edit display label for each
 *      param, and which parameterNames have no III catalog entry
 *      (FM9-divergent → deferred to an FM9-Edit Ghidra pass).
 *
 * The generated module re-exports the III catalog FILTERED to
 * FM9-present families at runtime (no table duplication) plus small
 * generated overlays (labels, UI-exposure set, unresolved list).
 *
 * Run:
 *   npx tsx scripts/_research/generate-fm9-params.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { PARAMS } from 'fractal-midi/axe-fx-iii';

interface XmlEntry {
  parameterName: string;
  displayLabel: string;
  controlType: string;
  blocks: string[];
  variants: string[];
}

const xml: XmlEntry[] = JSON.parse(
  readFileSync('samples/captured/decoded/fm9edit-xml-labels.json', 'utf-8'),
);

const catalogByName = new Map(PARAMS.map((p) => [p.name, p] as const));

const matched: Array<{ entry: XmlEntry; family: string }> = [];
const unresolved: XmlEntry[] = [];
for (const e of xml) {
  const hit = catalogByName.get(e.parameterName);
  if (hit) matched.push({ entry: e, family: hit.family });
  else unresolved.push(e);
}

const families = [...new Set(matched.map((m) => m.family))].sort();
const labelEntries = matched
  .map((m) => [m.entry.parameterName, m.entry.displayLabel] as const)
  .sort((a, b) => a[0].localeCompare(b[0]));

const familyCount = new Map<string, number>();
for (const m of matched) familyCount.set(m.family, (familyCount.get(m.family) ?? 0) + 1);

console.log(`XML entries:        ${xml.length}`);
console.log(`matched in III cat: ${matched.length} (${((matched.length / xml.length) * 100).toFixed(1)}%)`);
console.log(`unresolved:         ${unresolved.length}`);
console.log(`families present:   ${families.length}`);
if (unresolved.length > 0) {
  console.log('\nunresolved entries (no III catalog name match — deferred to FM9 Ghidra pass):');
  for (const u of unresolved) {
    console.log(`  ${u.parameterName.padEnd(40)} "${u.displayLabel}" [${u.blocks.join(', ')}]`);
  }
}

const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const out = `/**
 * FM9 parameter catalog — AUTO-GENERATED by
 *   scripts/_research/generate-fm9-params.ts
 * from the Axe-Fx III catalog (paramId addressing) joined against the
 * FM9-Edit BinaryData XML label mine
 * (\`mine-fm9edit-xml-labels.ts\`; raw artifacts gitignored under
 * samples/). DO NOT HAND-EDIT — re-run the generator to refresh.
 *
 * Provenance model:
 *   - **paramId addressing is III-shared.** The FM9 and Axe-Fx III
 *     share the firmware param-table lineage; this module re-exports
 *     the III catalog filtered to the ${families.length} families FM9-Edit's own
 *     layout XML exposes. No FM9-side Ghidra pass has run yet; param
 *     IDs are unverified-on-FM9 until read-back/calibration confirms
 *     them per family.
 *   - **Display labels are FM9-native.** \`FM9_DISPLAY_LABELS\` carries
 *     the label FM9-Edit's UI shows for each parameterName
 *     (${labelEntries.length} entries mined from __block_layout.xml +
 *     __amp_layout*.xml).
 *   - **Block→family corrections vs the III descriptor** (proven by
 *     which layout file each family appears in):
 *       AMP block   → DISTORT family (122 params in __amp_layout.xml)
 *       DRIVE block → FUZZ family    (42 params under the Drive section)
 *     The III's v1.4 "ID_DISTORT" appendix entry therefore names the
 *     AMP block's effect-ID range, not Drive's.
 *   - ${unresolved.length} FM9-Edit parameterName(s) had no III catalog match and are
 *     listed in \`FM9_UNRESOLVED_PARAMS\` (no paramId — needs an
 *     FM9-Edit Ghidra pass).
 *
 * Coverage: ${matched.length}/${xml.length} FM9-Edit XML parameterNames matched the III
 * catalog (${((matched.length / xml.length) * 100).toFixed(1)}%).
 */
import { PARAMS as III_PARAMS } from '../axe-fx-iii/params.js';
import type { Param } from '../axe-fx-iii/params.js';

export type { Param, Unit } from '../axe-fx-iii/params.js';

/** Families the FM9 exposes, per FM9-Edit's own layout XML. */
export const FM9_FAMILIES: readonly string[] = ${JSON.stringify(families)} as const;

const FAMILY_SET: ReadonlySet<string> = new Set(FM9_FAMILIES);

/**
 * The FM9 parameter catalog: the III catalog filtered to FM9-present
 * families. paramId addressing is III-shared (unverified-on-FM9 until
 * per-family read-back confirms).
 */
export const PARAMS: readonly Param[] = III_PARAMS.filter((p) => FAMILY_SET.has(p.family));

/** Params grouped by family symbol. */
export const PARAMS_BY_FAMILY: Readonly<Record<string, readonly Param[]>> = (() => {
  const map: Record<string, Param[]> = {};
  for (const p of PARAMS) (map[p.family] ??= []).push(p);
  return Object.freeze(map);
})();

/** \`(family, name)\` composite-key lookup (the unique key — see III catalog header). */
export const PARAM_BY_KEY: ReadonlyMap<string, Param> = new Map(
  PARAMS.map((p) => [\`\${p.family}/\${p.name}\`, p] as const),
);

/**
 * FM9-Edit display label per parameterName (the label under the knob
 * in FM9-Edit's UI). Only parameterNames present in both the FM9 XML
 * and the III catalog appear here.
 */
export const FM9_DISPLAY_LABELS: Readonly<Record<string, string>> = Object.freeze({
${labelEntries.map(([n, l]) => `  ${/^[A-Za-z_][A-Za-z0-9_]*$/.test(n) ? n : `'${esc(n)}'`}: '${esc(l)}',`).join('\n')}
});

/**
 * parameterNames FM9-Edit's UI exposes (subset of the catalog —
 * the catalog also carries non-UI params from the III dispatcher
 * tables).
 */
export const FM9_UI_PARAM_NAMES: ReadonlySet<string> = new Set(
  Object.keys(FM9_DISPLAY_LABELS),
);

/**
 * FM9-Edit parameterNames with NO III catalog entry. No paramId is
 * known for these — they are NOT wire-addressable until an FM9-Edit
 * Ghidra pass mines their IDs. Kept for visibility.
 */
export const FM9_UNRESOLVED_PARAMS: readonly {
  parameterName: string;
  displayLabel: string;
  controlType: string;
  blocks: readonly string[];
}[] = ${JSON.stringify(unresolved.map((u) => ({
  parameterName: u.parameterName,
  displayLabel: u.displayLabel,
  controlType: u.controlType,
  blocks: u.blocks,
})), null, 2)};
`;

writeFileSync('packages/fractal-midi/src/fm9/params.ts', out, 'utf-8');
console.log(`\nwrote packages/fractal-midi/src/fm9/params.ts (${families.length} families, ${labelEntries.length} labels, ${unresolved.length} unresolved)`);
