/**
 * Parse the output of `MineAxeEditIII.java` (Ghidra dump) and extract
 * structured findings — the parts of the dump that map directly to
 * protocol decode.
 *
 * Specifically:
 *   1. From SECTION B (SYSEX_* string-pool xrefs): identify the
 *      enum-name-lookup function (the one referencing all 23 SYSEX_*
 *      strings) and extract its switch (fn) cases, giving us function-
 *      byte → SYSEX_* name for every entry in the binary.
 *   2. From SECTION A (F0 00 01 74 10 emitters): identify the message-
 *      builder helpers and their per-function wrappers; transcribe the
 *      function-byte and payload layout for the undocumented opcodes.
 *   3. From SECTION C (MIDI_ERROR_* xrefs): the function that handles
 *      0x64 responses; cross-check our 28-code table against the
 *      decompile.
 *   4. From SECTION E2 / E3: param-symbol resolver hints.
 *
 * Output: structured markdown in samples/captured/decoded/
 *   ghidra-axeedit3-findings.md plus per-table JSON files where
 *   appropriate.
 *
 * The parser is best-effort: Ghidra's decompile output isn't pure
 * machine-readable, so we use heuristic regex patterns that work on
 * typical decompiler output. Anomalies get flagged but not blocked.
 *
 * Run AFTER the founder runs MineAxeEditIII.java in Ghidra:
 *   npx tsx scripts/_research/parse-ghidra-axeedit3-mine.ts
 *     [--in samples/captured/decoded/ghidra-axeedit3-mine.txt]
 *     [--out samples/captured/decoded/ghidra-axeedit3-findings.md]
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const args = process.argv.slice(2);
function flag(name: string, fallback?: string): string | undefined {
  const i = args.indexOf(`--${name}`);
  if (i < 0 || i + 1 >= args.length) return fallback;
  return args[i + 1];
}

const inPath = flag('in', 'samples/captured/decoded/ghidra-axeedit3-mine.txt')!;
const outPath = flag('out', 'samples/captured/decoded/ghidra-axeedit3-findings.md')!;

if (!existsSync(inPath)) {
  console.error(`Input file not found: ${inPath}`);
  console.error('Run MineAxeEditIII.java in Ghidra first to produce the dump.');
  process.exit(1);
}

const raw = readFileSync(inPath, 'utf-8');
console.log(`loaded ${raw.length.toLocaleString()} bytes from ${inPath}`);

// ── Split into sections ────────────────────────────────────────────

interface Section {
  name: string;
  body: string;
}

const SECTION_HEADER_RE = /^={80}\nSECTION ([A-Z0-9]+) — (.+)\n={80}$/gm;

const sectionMatches = [...raw.matchAll(SECTION_HEADER_RE)];
const sections: Section[] = [];
for (let i = 0; i < sectionMatches.length; i++) {
  const m = sectionMatches[i];
  const next = sectionMatches[i + 1];
  const start = m.index! + m[0].length;
  const end = next ? next.index! : raw.length;
  sections.push({
    name: `SECTION ${m[1]} — ${m[2]}`,
    body: raw.slice(start, end),
  });
}
console.log(`found ${sections.length} sections`);
for (const s of sections) console.log(`  ${s.name} (${s.body.length} bytes)`);

const out: string[] = [];
function w(line = '') {
  out.push(line);
}

w('# Ghidra extraction findings — AxeEdit III');
w('');
w('Parsed from `' + inPath + '`.');
w('Generated by `scripts/_research/parse-ghidra-axeedit3-mine.ts`.');
w('');

// ── Helpers ────────────────────────────────────────────────────────

function findSection(prefix: string): Section | undefined {
  return sections.find((s) => s.name.startsWith(prefix));
}

// Extract "function FUN_xxxxxxxx @ Address" blocks from a section.
// Each block runs from "[LABEL] FunctionName @ Address" until the next
// "[LABEL]" or end-of-section.
interface FunctionDump {
  label: string;
  funcName: string;
  address: string;
  body: string;
}

function extractFunctionDumps(body: string): FunctionDump[] {
  const dumps: FunctionDump[] = [];
  // Pattern: "[LABEL] funcName @ address" or "# [LABEL] funcName @ address"
  const re = /(?:^|\n)#*\s*\[([^\]]+)\]\s+(\S+)\s+@\s+([0-9a-fA-F]+)/g;
  const hits = [...body.matchAll(re)];
  for (let i = 0; i < hits.length; i++) {
    const start = hits[i].index! + hits[i][0].length;
    const end = i + 1 < hits.length ? hits[i + 1].index! : body.length;
    dumps.push({
      label: hits[i][1],
      funcName: hits[i][2],
      address: hits[i][3],
      body: body.slice(start, end),
    });
  }
  return dumps;
}

// Heuristic: detect a switch/case statement and pull (caseValue, label).
// Ghidra decompiles switches as nested if/else-if (when the case bodies
// are simple) or as actual `switch` blocks (when the optimizer made a
// jump table). Try both.
function extractSwitchCases(c: string): Array<{ caseValue: number; bodySnippet: string }> {
  const cases: Array<{ caseValue: number; bodySnippet: string }> = [];

  // Pattern 1: actual switch/case
  // case 0xN: <body>
  // case N: <body>
  const switchRe = /case\s+(0x[0-9a-fA-F]+|\d+)\s*:\s*\n([\s\S]*?)(?=case\s+(?:0x[0-9a-fA-F]+|\d+)\s*:|default\s*:|break\s*;|return\s)/g;
  for (const m of c.matchAll(switchRe)) {
    const v = parseInt(m[1], m[1].startsWith('0x') ? 16 : 10);
    cases.push({ caseValue: v, bodySnippet: m[2].trim().slice(0, 200) });
  }
  if (cases.length > 0) return cases;

  // Pattern 2: if/else-if chain (e.g. `if (fn == 0x0A) return "SYSEX_SETGET_BYPASS"`)
  const ifRe = /(?:if|else\s+if)\s*\(\s*\w+\s*==\s*(0x[0-9a-fA-F]+|\d+)\s*\)\s*\{?\s*([^}]{1,200})/g;
  for (const m of c.matchAll(ifRe)) {
    const v = parseInt(m[1], m[1].startsWith('0x') ? 16 : 10);
    cases.push({ caseValue: v, bodySnippet: m[2].trim().slice(0, 200) });
  }
  return cases;
}

// ── Section B parsing — SYSEX_* enum-name lookup ──────────────────

const sectionB = findSection('SECTION B');
w('## SYSEX_* function-byte lookup (Section B)');
w('');
if (!sectionB) {
  w('_Section B not present in the dump._');
  w('');
} else {
  // Find the "[SYSEX_LOOKUP, N strings]" function with the highest N.
  // Decompile body follows. Extract switch cases.
  const dumps = extractFunctionDumps(sectionB.body);
  const lookups = dumps.filter((d) => d.label.startsWith('SYSEX_LOOKUP'));
  if (lookups.length === 0) {
    w('_No `[SYSEX_LOOKUP, N strings]` function found in Section B._');
  } else {
    const top = lookups[0];
    w(`Top SYSEX_* lookup: \`${top.funcName} @ ${top.address}\` (${top.label}).`);
    w('');
    const cases = extractSwitchCases(top.body);
    if (cases.length > 0) {
      w(`Extracted ${cases.length} switch case${cases.length === 1 ? '' : 's'}:`);
      w('');
      w('| fn byte | string returned / case body (truncated) |');
      w('|---|---|');
      for (const c of cases.sort((a, b) => a.caseValue - b.caseValue)) {
        const fnHex = '0x' + c.caseValue.toString(16).padStart(2, '0');
        // Try to extract the string literal from the case body
        const strMatch = c.bodySnippet.match(/"(SYSEX_[A-Z0-9_]+)"/);
        const label = strMatch ? '`' + strMatch[1] + '`' : '`' + c.bodySnippet.slice(0, 80).replace(/\|/g, '\\|') + '`';
        w(`| ${fnHex} | ${label} |`);
      }
      w('');
      w('**This table gives function-byte → SYSEX_* symbol-name mapping for every');
      w('III SysEx function the AxeEdit source defines, including undocumented');
      w('ones. Use this to extend `docs/devices/axe-fx-iii/SYSEX-MAP.md`.**');
    } else {
      w('_No switch/case pattern recognized in the lookup body. Hand-inspect the body:_');
      w('');
      w('```c');
      w(top.body.slice(0, 4000));
      if (top.body.length > 4000) w('… (truncated)');
      w('```');
    }
  }
  w('');

  // List per-function builders (label starts with "BUILDER for ").
  const builders = dumps.filter((d) => d.label.startsWith('BUILDER for'));
  if (builders.length > 0) {
    w('### Singleton-referencer builders (per-function message wrappers)');
    w('');
    w('Each of these references exactly one `SYSEX_*` string — they\'re the');
    w('per-function message builders for the named opcode. Cross-check the');
    w('payload layout against `docs/devices/axe-fx-iii/SYSEX-MAP.md`.');
    w('');
    for (const b of builders) {
      w(`- **${b.label}** — \`${b.funcName} @ ${b.address}\``);
    }
    w('');
  }
}

// ── Section A parsing — F0-00-01-74-10 emitters ───────────────────

const sectionA = findSection('SECTION A');
w('## SysEx header emitters (Section A)');
w('');
if (!sectionA) {
  w('_Section A not present in the dump._');
  w('');
} else {
  // Extract the byte-pattern hit count.
  const hitsMatch = sectionA.body.match(/Byte-pattern hits:\s*(\d+)/);
  if (hitsMatch) w(`Byte-pattern \`F0 00 01 74 10\` hits: ${hitsMatch[1]}.`);
  const distinctMatch = sectionA.body.match(/Distinct emitting functions:\s*(\d+)/);
  if (distinctMatch) w(`Distinct emitting functions: ${distinctMatch[1]}.`);
  w('');
  // List the emitter functions
  const dumps = extractFunctionDumps(sectionA.body);
  const emitters = dumps.filter((d) => d.label === 'EMITTER');
  if (emitters.length > 0) {
    w('### Emitters');
    w('');
    for (const e of emitters) {
      w(`- \`${e.funcName} @ ${e.address}\``);
    }
    w('');
  }
}

// ── Section C parsing — MIDI_ERROR_* xrefs ────────────────────────

const sectionC = findSection('SECTION C');
w('## MIDI_ERROR_* response handler (Section C)');
w('');
if (!sectionC) {
  w('_Section C not present in the dump._');
  w('');
} else {
  const dumps = extractFunctionDumps(sectionC.body);
  if (dumps.length > 0) {
    w(`${dumps.length} function${dumps.length === 1 ? '' : 's'} reference the MIDI_ERROR_* anchors:`);
    w('');
    for (const d of dumps) {
      w(`- **${d.label}** — \`${d.funcName} @ ${d.address}\``);
    }
    w('');
    w('Check the top entry against our Session 81 `describeMultipurposeResultCode`');
    w('— the function body should either be a switch (idx → string) or a const');
    w('char* table lookup. Either form confirms the 28-code mapping.');
  }
  w('');
}

// ── Section D — msg_* xrefs ───────────────────────────────────────

const sectionD = findSection('SECTION D');
w('## Format-string anchor xrefs (Section D)');
w('');
if (!sectionD) {
  w('_Section D not present in the dump._');
  w('');
} else {
  const dumps = extractFunctionDumps(sectionD.body);
  if (dumps.length > 0) {
    w(`${dumps.length} function${dumps.length === 1 ? '' : 's'} reference msg_* format strings:`);
    w('');
    for (const d of dumps) {
      w(`- **${d.label}** — \`${d.funcName} @ ${d.address}\``);
    }
    w('');
    w('Each function is a candidate for AxeEdit\'s per-block param-info query.');
    w('Decompile body has the request shape (which fields it sends, how it parses');
    w('the response). Cross-reference with `msg_getBlockString` / `msg_getParamInfo`');
    w('format strings to identify the wire envelope.');
  }
  w('');
}

// ── Section E2 — param-symbol resolver hints ──────────────────────

const sectionE2 = findSection('SECTION E2');
w('## Parameter-symbol resolver (Section E2)');
w('');
if (!sectionE2) {
  w('_Section E2 not present in the dump._');
  w('');
} else {
  const dumps = extractFunctionDumps(sectionE2.body);
  if (dumps.length > 0) {
    w(`${dumps.length} function${dumps.length === 1 ? '' : 's'} reference parameter-symbol anchors:`);
    w('');
    for (const d of dumps.slice(0, 20)) {
      w(`- **${d.label}** — \`${d.funcName} @ ${d.address}\``);
    }
    if (dumps.length > 20) w(`- … (${dumps.length - 20} more)`);
    w('');
    w('Recommend running `MineAxeEditIIIParamResolver.java` for the focused');
    w('rank-by-symbol-count analysis — it identifies the single resolver function');
    w('with full decompile.');
  }
  w('');
}

// ── Done ──────────────────────────────────────────────────────────

writeFileSync(outPath, out.join('\n'));
console.log(`\nwrote ${out.length} lines to ${outPath}`);
