/**
 * Hydrasynth Explorer agent guidance — migrated from the long device-
 * namespaced tool descriptions in `src/asm/hydrasynth-explorer/tools/
 * {params,patch,navigation,discovery}.ts`.
 *
 * v0.3 removed several device-namespaced tools (hydra_switch_patch,
 * hydra_set_engine_param/s, hydra_param_catalog, hydra_list_enum_values);
 * the LLM no longer sees those guidance blocks through tool descriptions.
 * They surface instead via `describe_device({ port: 'hydrasynth' }).
 * agent_guidance`.
 */

export const HYDRASYNTH_AGENT_GUIDANCE: Readonly<Record<string, string>> = {
  patch_recipes: [
    'PATCH RECIPES: for "give me a <bass/pad/lead/e-piano/brass/...> sound"',
    'or a named iconic tone, prefer apply_patch({recipe_id}) over authoring',
    'params from scratch. Discover available ids + their category /',
    'description / tags via describe_device("hydrasynth").recipes. Merge tweaks',
    'with apply_patch({recipe_id, overrides:{filter1cutoff:90,...}}). Recipes',
    'are grouped by the device\'s own category tags (Bass, Pad, Lead, E-piano,',
    'Brass, Keys, Arp, ...). A recipe with requires_nrpn:true also wires',
    'macro / mod-matrix routes after the patch dump; those need Param TX/RX =',
    'NRPN (the base patch lands over SysEx regardless). recipes[] lists only',
    'hardware-confirmed recipes; the founder may name an unverified id to',
    'audition — apply_patch resolves any valid recipe_id.',
  ].join(' '),

  device_precondition: [
    'IMPORTANT, DEVICE PRECONDITION: NRPN engine-param writes (the unified',
    'set_param / set_params surface, plus set_mod_route / set_macro_route)',
    'only respond when Param TX/RX is set to NRPN on System Setup → MIDI',
    'page 10. If writes seem inert, check that first. System CCs (master',
    'volume, sustain pedal, etc.; call set_system_param for those) work',
    'regardless of the Param TX/RX setting.',
    '',
    'CC vs NRPN ARE MUTUALLY EXCLUSIVE: Param TX/RX is a single global mode',
    '(CC, NRPN, or Off). set_macro drives Macros 1-8 over CC 16-23 and needs',
    'CC mode; the NRPN tools above need NRPN mode. You CANNOT author a macro',
    'destination (set_macro_route, NRPN) and then drive it live with',
    'set_macro (CC) without switching the device mode between the two. If the',
    'user wants both author-then-audition in one session, tell them to set',
    'Param TX/RX = NRPN to wire routes, then = CC to drive the macro (or just',
    'turn the physical macro knob to audition). There is no single mode that',
    'serves both.',
  ].join(' '),

  ack_caveat: [
    'No wire-ack: consumer MIDI synths don\'t echo NRPN. Confirmation is',
    'audible / observable on the device only. The set_param response says',
    'acked=true to signal "wire bytes sent successfully"; it does NOT',
    'confirm the device actually applied the change.',
  ].join(' '),

  volume_language: [
    'When the user says "louder / quieter / wetter", pick the right knob:',
    '`amplevel` is the main output trim (0..128), `mixer.osc{1,2,3}_vol`',
    'is per-oscillator level (drive into the filter), `<fx>.dry_wet` /',
    '`<fx>wet` (prefx / delay / reverb / postfx / mutator) is each FX\'s',
    'wet/dry mix (0..100%). Hydrasynth is a synth so there\'s no "input',
    'gain"; oscillator level is the closest analog. Full cheat sheet:',
    'docs/VOLUME-CONTROL.md.',
  ].join(' '),

  param_name_aliases: [
    'Both NRPN canonical names ("filter1type", "osc1semi", "prefxtype",',
    '"env1attacksyncoff") and CC-style aliases ("filter1.cutoff",',
    '"mixer.osc1_vol", "env1.attack") resolve via set_param. Skip the',
    'list_params discovery step for normal tweaks; the unified resolver',
    'accepts whichever form the agent / user types.',
  ].join(' '),

  macro_model: [
    'Macros 1-8 (CCs 16-23) are patch-defined: each loaded patch wires',
    'its 8 Macros to whatever synthesis parameters the patch designer',
    'chose, via the mod matrix. So "Macro 1" might be filter sweep on one',
    'patch and reverb mix on another; there\'s no fixed mapping. Macros',
    'are an excellent first lever for tone tweaks because they\'re curated',
    'by the patch designer to be musically useful for that patch. Use the',
    'set_macro tool to drive them (sends CC 16-23; needs Param TX/RX = CC).',
    'To AUTHOR which synthesis param a macro moves on an agent-built patch,',
    'use set_macro_route (NRPN; needs Param TX/RX = NRPN). These two modes',
    'are mutually exclusive, see device_precondition.',
  ].join(' '),

  fresh_build_vs_tweak: [
    'For FRESH-PATCH BUILDS use apply_patch (atomic SysEx, starts',
    'from the factory INIT buffer so all hardwired routings (env1 → VCA,',
    'mod matrix, mutators) are intact by construction). For INCREMENTAL',
    'tweaks on top of an already-loaded patch, use set_param / set_params',
    '(NRPN writes). NRPN sequences can\'t replace destructively-set state',
    'from a prior patch; recipes fail in subtle ways ("fizzy attack then',
    'silence" if env→VCA is missing) when you try whole-patch builds via',
    'sequential NRPN writes.',
  ].join(' '),

  patch_addressing: [
    'Patches are addressed by Bank+Patch: "A001".."H128" form (letter',
    'A..H + patch 1..128). 1024 total locations (8 banks × 128).',
    'switch_preset uses Bank Select MSB=0 + LSB=bank + Program Change=patch.',
    'No SysEx-level "get patch name" primitive on Hydrasynth, so',
    'scan_locations is not supported.',
  ].join(' '),

  audition_slot_honesty: [
    'When apply_patch is called WITHOUT a slot argument, the patch',
    'lands in the WORKING BUFFER only; no slot is touched, no save',
    'happens. Do NOT narrate this as "loading to H128" or any other slot;',
    'the device is auditioning the change in RAM and will revert on the',
    'next patch load. Say "loaded into the working buffer" (or simply',
    '"loaded for audition"). H128 is the conventional scratch slot on',
    'AM4 and does not apply on Hydrasynth; there is no scratch slot',
    'convention here, only working-buffer-vs-saved-slot.',
  ].join(' '),

  diagnostic_isolation: [
    'When the user reports an unwanted sound in a recently-built patch',
    '(stray ringing, pitch creep, wash on the tail, weird tail artifact),',
    'isolate via set_bypass: toggle one FX block at a time (prefx /',
    'postfx / delay / reverb / mutator1..4) and ask the user to play',
    'between toggles before changing any param values. Bulk edits across',
    'multiple FX during diagnosis make it impossible to tell which',
    'change mattered. Batching is correct for confident builds;',
    'isolation is the right tool for chasing artifacts.',
  ].join(' '),

  loudness: [
    'LOUDNESS MODEL on the Hydrasynth. Hydrasynth is a synth, not an amp',
    'modeler, so the loudness story is OSCILLATOR STACK → MIXER → FILTER →',
    'AMP → FX → MASTER, not "amp gain / master / level" the way the Fractal',
    'devices have it. All values are DISPLAY UNITS thanks to the NRPN-derived',
    'display calibration (see nrpnDisplay.ts in the package).',
    '',
    'The knobs that move loudness, top-to-bottom by influence:',
    '',
    '  amplevel               0..128 knob   Post-amp output trim. The single',
    '                                       biggest lever on overall patch',
    '                                       loudness; sits downstream of the',
    '                                       filter and upstream of the FX chain.',
    '                                       INIT patches land near ~100. BUT a',
    '                                       low filter1cutoff is a common cause',
    '                                       of a dark/quiet patch (a closed',
    '                                       filter passes almost nothing above',
    '                                       the fundamental), so for "too quiet"',
    '                                       check filter1cutoff FIRST; only if',
    '                                       cutoff is already open does pushing',
    '                                       amplevel toward 120-128 help.',
    '  mixerosc1vol           0..128 knob   Per-oscillator level into the',
    '  mixerosc2vol                         filter. OSC 1 defaults loud (100)',
    '  mixerosc3vol                         on a fresh INIT, OSC 2 and OSC 3',
    '                                       default to 0. Setting both 1 and 2',
    '                                       to 128 stacks them in phase and',
    '                                       OFTEN CLIPS; drop each to ~80-90',
    '                                       when stacking, or use one as the',
    '                                       fundamental and the other as a',
    '                                       detuned partial.',
    '  mixernoisevol          0..128 knob   Noise generator level. Useful for',
    '                                       attack transients and breath/wind',
    '                                       textures. Subtractive synthesis',
    '                                       convention: small amounts (10-30)',
    '                                       for bite, larger amounts for',
    '                                       wind / pink-noise patches.',
    '  mixerringmodvol        0..128 knob   Ring-mod block level (osc1 × osc2',
    '                                       by default; ringmodsource1/2 picks',
    '                                       sources). Ring mod produces sum and',
    '                                       difference frequencies. Adds',
    '                                       harmonics that READ LOUDER at the',
    '                                       same RMS than pure oscillator tone.',
    '                                       Pulling ringmod into the mix at 30+',
    '                                       is often enough to make a patch',
    '                                       feel louder without touching',
    '                                       amplevel.',
    '  ringmoddepth           0..128 knob   Depth of the ring-mod modulation',
    '                                       itself (independent from its mixer',
    '                                       level). High depth + high mix is a',
    '                                       common loudness/harshness pairing.',
    '  filter1drive           0..128 knob   In-filter overdrive. Pushes the',
    '                                       filter into nonlinear saturation;',
    '                                       adds perceived loudness AND tone',
    '                                       character. Closest Hydra analog to',
    '                                       "amp gain" on a Fractal device.',
    '  filter1cutoff          0..128 knob   Filter cutoff frequency. Not a',
    '                                       direct loudness control, but with',
    '                                       resonance > ~40 a high cutoff',
    '                                       sweeps a resonant peak through the',
    '                                       audible range and READS LOUDER. See',
    '                                       cross-param interactions below.',
    '  prefxwet               0..100 %      Pre-FX block dry/wet (sits between',
    '                                       voice and amp). For Lo-Fi pre-FX,',
    '                                       prefxparam4 is MAKEUP GAIN in dB',
    '                                       (-6..+36); the internal Lo-Fi filter',
    '                                       (prefxparam1 Cutoff Hz) can KILL',
    '                                       signal if set below the playing',
    '                                       fundamental. Keep it well above the',
    '                                       highest note, then add makeup with',
    '                                       prefxparam4.',
    '  mutator1wet..4wet      0..100 %      Per-mutator wet mix. Mutators are',
    '                                       FM / wave-shaping units; raising',
    '                                       their wet adds harmonic content and',
    '                                       perceived loudness, but heavy',
    '                                       mutation can also fold harmonics',
    '                                       back into the noise floor.',
    '  delaywet               0..100 %      Wet/dry of the delay block. 20-35%',
    '                                       for rhythmic Edge-style delays;',
    '                                       lower for subtle thickening.',
    '  reverbwet              0..100 %      Wet/dry of the reverb. 25-40% is a',
    '                                       normal room/plate range; above 50%',
    '                                       washes the patch and masks the',
    '                                       attack transient.',
    '  postfxwet              0..100 %      Post-FX block dry/wet (after reverb).',
    '                                       Last stop before master.',
    '  system.master_volume   0..127 CC     GLOBAL master volume (MIDI CC 7).',
    '                                       SYSTEM-WIDE, not per-patch; affects',
    '                                       every patch and persists across',
    '                                       patch loads. Use for stage-wide',
    '                                       level only. Send via set_system_param',
    '                                       (system param), not the engine NRPN',
    '                                       surface.',
    '',
    'CROSS-PARAM INTERACTIONS (synth-engineering rules of thumb):',
    '',
    '  - filter1cutoff + filter1resonance interact: with resonance > ~40, a',
    '    high cutoff sweeps a resonant peak through the audible range and the',
    '    patch READS LOUDER even with the same amplevel. Lowering cutoff with',
    '    high resonance can swallow the fundamental. For loudness-stable',
    '    filter sweeps, keep resonance under ~30.',
    '  - Ring mod adds sum-and-difference partials that read louder for the',
    '    same RMS than pure oscillator tone. Bringing mixerringmodvol into the',
    '    mix at 30+ often makes a patch feel louder without changing amplevel,',
    '    AND adds harmonic interest. Easy first lever for "this patch needs',
    '    more presence."',
    '  - Stacking osc1 + osc2 at the same pitch with both volumes near 128',
    '    OFTEN CLIPS the mixer. Either detune one (osc2cent +/-7..15) for a',
    '    chorus-stack effect at moderate level, or drop each to ~80-90 before',
    '    stacking. If the patch sounds distorted with no FX engaged, mixer',
    '    clipping is the most common cause.',
    '  - filter1drive is the Hydra analog of "amp gain": adds nonlinear',
    '    saturation AND lifts perceived loudness. For "more presence/grit but',
    '    same level", raise filter1drive by ~20-30 and drop amplevel by ~10-15.',
    '  - reverbwet above 50% masks 1-3 kHz mid-range and swallows the attack',
    '    transient. Pads tolerate this; lead patches do not. If the user says',
    '    "the lead lost its bite after I added reverb", pull reverbwet back to',
    '    25-35%.',
    '',
    'MACROS (1-8, CCs 16-23) AS LOUDNESS LEVERS. Macros are patch-defined:',
    'each loaded patch wires its 8 macros to whatever synthesis parameters the',
    'patch designer chose via the mod matrix. So Macro 1 might be filter sweep',
    'on one patch and reverb mix on another; there is no fixed mapping. On a',
    'BLANK / INIT patch the macros are unmapped, so driving them does',
    'NOTHING until the user (or apply_patch) wires them to a target via',
    'macroNtargetM. Do not narrate "raised Macro 1 to make it louder" on an',
    'init patch; it will silently no-op. On factory patches the macros are',
    'typically curated to be musically useful and ARE a great first lever for',
    'tone tweaks; use set_macro to drive them (CC 16-23; needs Param TX/RX = CC).',
    '',
    'PATCH LEVELING (no scenes on Hydra). The Hydrasynth has no per-scene',
    'concept like the Fractal devices, so you can NOT do AM4-style scene-',
    'relative balance with one knob. Loudness lives at the patch level: build',
    'each patch to land within roughly +/- 3 dB of the others in the bank, via',
    'amplevel as the primary trim. For multi-patch performance sets, audition',
    'patches in sequence (switch_preset and ask the user to play each) and',
    'adjust amplevel on the quieter patches; do NOT touch system.master_volume',
    'between patches (CC 7 is global and the user will lose their headroom',
    'reference).',
    '',
    'WIRE CALIBRATION NOTE. The Hydra exposes most loudness knobs on a',
    '0..8192 NRPN wire range, displayed as 0..128 (or 0..100 % for FX wets).',
    'The descriptor handles the wire-to-display mapping for you; pass display',
    'units to set_param and read display units back from the device label. If',
    'you ever see a raw wire integer in a response, that is a calibration bug',
    'worth filing, not the convention.',
  ].join('\n'),

  envelope_time_units: [
    'Envelope time params (env1..5 {attack,decay,release,hold,delay}syncoff)',
    'accept values 0..127 as knob units. The wire→time mapping is',
    'piecewise: fine 1ms steps near zero, doubling step size per bucket,',
    'topping out at 36s (attack/hold), 32s (delay), or 60s (decay/release).',
    'The unified set_param / set_params and apply_patch tool responses',
    'carry a `deviceLabel` field with the EXACT string the device LCD',
    'shows (e.g. "5.12 Sec", "320 ms", "44.0 Sec"); narrate from that,',
    'never from your own calculation. Hardware-verified 2026-05-17: all',
    '27 sampled points across env2 attack/decay/release at',
    'N ∈ {0,5,10,25,50,75,100,120,127} matched device display exactly.',
    'Decay and release share the same table; attack and hold share a',
    'different (shorter) table. N=127 falls one bucket short of the',
    'absolute max; pass 128 to reach it. Relative language ("longer',
    'release", "slower attack") is still good UX, but absolute',
    'narration is now truthful as long as it comes from deviceLabel.',
  ].join(' '),

  tempo_time_discipline: [
    'TEMPO-FIRST for time-based params. Tempo-synced timing is the PROFESSIONAL',
    'DEFAULT for rhythmic music, prefer it over raw ms/Hz unless the user asks',
    'for a specific number, a free-time / slapback feel, or there is no tempo',
    'reference.',
    'DELAY: for rhythmic music ("ambient", "Edge / U2", "post-rock", "worship",',
    '"atmospheric"), set `delaybpmsync:1` and pass `delaytimesyncon` as a musical',
    'division ("1/4 D" dotted-quarter Edge sound, "1/4" clear quarters, "1/2 D"',
    'ambient wash, "1/8 D" / "1/8" / "1/16"). Use `delaybpmsync:0` + `delaytimesyncoff`',
    '(raw ms) only for explicit ms / free-time / slapback. The bpmsync flag selects',
    'which the device reads, so ALWAYS set the flag and the matching time param in',
    'the same call; setting `delaytimesyncon` while `delaybpmsync:0` has no audible',
    'effect (and vice-versa).',
    'LFO 1..5: for rhythmic modulation (rhythmic wobble, synced tremolo / filter',
    'sweeps) set `lfoNbpmsync:1` and pass `lfoNratesyncon` as a division; free-Hz',
    '`lfoNratesyncoff` is the textural default for non-rhythmic shimmer / drift.',
    'Same flag-selects-interpretation rule, set both together. The same applies to',
    'LFO delay (`lfoNdelaysyncon` vs `lfoNdelaysyncoff`).',
  ].join(' '),
};
