/**
 * Generate `packages/fractal-midi/src/gen3/fm9/rosters.generated.ts` — the
 * device-true FM9 enum rosters (amp / drive-FUZZ / reverb type), mined from an
 * FM9-Edit `effectDefinitions_12_<fw>.cache` and validated against the
 * hardware-confirmed ordinal anchors before emission.
 *
 * The cache is a sequence of `[uint32 LE length][ASCII name]` records; each
 * effect's model roster is a contiguous run in ordinal order (run index i ==
 * model ordinal i). A greedy walk MERGES adjacent tables, so we anchor on a
 * KNOWN name, walk backward to the table start, forward to the end, and assert
 * the confirmed ordinals land correctly. A self-validating `uint32` entry-count
 * sits immediately before each table.
 *
 * The `.cache` is gitignored (local debug scratch); this script's OUTPUT (the
 * generated .ts) is committed. Re-run when a newer firmware cache arrives:
 *   npx tsx scripts/gen-fm9-rosters-from-cache.ts [path-to-cache]
 *
 * Validated 2026-06-09 against community FM9 fw 11.0 cache (D. MacVicar):
 *   amp 65=SV Bass 2 / 179=Texas Star Clean / 264=SV Bass 1 (hardware)
 *   FUZZ 15=Blues OD / 36=Blackglass 7K (hardware)
 *   reverb 16=Medium Spring / 45=Music Hall (documented gen-3 points)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const CACHE = process.argv[2]
  ?? resolve(root, 'samples/captured/fm9-community-2026-06-09/effectDefinitions_12_11p0.cache');
const OUT = resolve(root, 'packages/fractal-midi/src/gen3/fm9/rosters.generated.ts');

function recAt(buf: Buffer, off: number): { name: string; next: number } | undefined {
  if (off < 0 || off + 4 > buf.length) return undefined;
  const L = buf.readUInt32LE(off);
  if (L < 1 || L > 48 || off + 4 + L > buf.length) return undefined;
  for (let k = 0; k < L; k++) {
    const c = buf[off + 4 + k];
    if (c < 0x20 || c >= 0x7f) return undefined;
  }
  return { name: buf.toString('ascii', off + 4, off + 4 + L).replace(/\s+$/u, ''), next: off + 4 + L };
}

/** Anchor on `anchor`, walk back to the table start, forward to its end. */
function extractRoster(buf: Buffer, anchor: string): string[] {
  const needle = Buffer.from(anchor, 'ascii');
  let pos = -1;
  for (let i = buf.indexOf(needle); i >= 0; i = buf.indexOf(needle, i + 1)) {
    const r = recAt(buf, i - 4);
    if (r && r.name === anchor) { pos = i - 4; break; }
  }
  if (pos < 0) throw new Error(`anchor not found as a clean record: ${anchor}`);
  // back-walk to table start
  let start = pos;
  for (;;) {
    let prev: number | undefined;
    for (let plen = 1; plen <= 48; plen++) {
      const po = start - 4 - plen;
      const r = recAt(buf, po);
      if (r && r.next === start) { prev = po; break; }
    }
    if (prev === undefined) break;
    start = prev;
  }
  // forward-walk to end
  const names: string[] = [];
  let off = start;
  for (let r = recAt(buf, off); r; r = recAt(buf, off)) { names.push(r.name); off = r.next; }
  return names;
}

function assertAnchors(label: string, names: string[], anchors: Record<number, string>): void {
  for (const [k, v] of Object.entries(anchors)) {
    const got = names[Number(k)];
    if (got !== v) throw new Error(`${label}: ordinal ${k} expected "${v}" got "${got}" (count=${names.length})`);
  }
}

function toMap(names: string[]): string {
  return '{\n' + names.map((n, i) => `  ${i}: ${JSON.stringify(n)},`).join('\n') + '\n}';
}

const buf = readFileSync(CACHE);
const amp = extractRoster(buf, 'SV Bass 2');
const fuzz = extractRoster(buf, 'Blues OD');
const reverb = extractRoster(buf, 'Medium Spring');

assertAnchors('AMP', amp, { 65: 'SV Bass 2', 179: 'Texas Star Clean', 264: 'SV Bass 1' });
assertAnchors('FUZZ', fuzz, { 15: 'Blues OD', 36: 'Blackglass 7K' });
assertAnchors('REVERB', reverb, { 16: 'Medium Spring', 45: 'Music Hall' });

const banner = `// GENERATED by scripts/gen-fm9-rosters-from-cache.ts — DO NOT EDIT BY HAND.
// Source: FM9-Edit effectDefinitions cache (FM9 firmware 11.0, community capture
// 2026-06-09). Each roster is the device's own model list in ordinal order; the
// ordinal IS the gen-3 discrete-SET value, so these are read labels AND settable
// by name. Validated against hardware/documented anchors at generation time
// (amp 65/179/264, FUZZ 15/36, reverb 16/45). Re-run the script to regenerate.
/* eslint-disable */
`;

const body = `${banner}
/** FM9 amp model roster (DISTORT block type selector). ${amp.length} models. */
export const FM9_AMP_ROSTER: Readonly<Record<number, string>> = ${toMap(amp)};

/** FM9 drive/fuzz model roster (FUZZ block type selector). ${fuzz.length} models. */
export const FM9_DRIVE_ROSTER: Readonly<Record<number, string>> = ${toMap(fuzz)};

/** FM9 reverb type roster (REVERB block type selector). ${reverb.length} types. */
export const FM9_REVERB_TYPE_ROSTER: Readonly<Record<number, string>> = ${toMap(reverb)};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT}`);
console.log(`  amp=${amp.length}  drive/fuzz=${fuzz.length}  reverb=${reverb.length}  (all anchors validated)`);
