/**
 * Generate the committed gen-1 (Ultra) codec data from the validated research
 * pipeline output, so params.ts / blockTypes.ts are reproducible, never
 * hand-transcribed (project rule: spec/hardware dump over hand-edit).
 *
 * Pipeline:
 *   docs/manuals/AxeFx-Ultra-SysEx-Messages.htm
 *     -> scripts/_research/parse-gen1-sysex.ts        (params.json, blockTypes.json; 0-mismatch validated)
 *     -> scripts/_research/gen1-canonicalize.ts       (canonical-params.json; snake_case keys + scaling flags)
 *     -> THIS generator                               (src/axe-fx-gen1/{params,blockTypes}.ts)
 *
 *   cd packages/fractal-midi && npx tsx scripts/generate-gen1-catalog.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');
const RESEARCH = join(REPO, 'scripts', '_research', 'gen1-out');
const OUT = join(HERE, '..', 'src', 'axe-fx-gen1');

interface CanonParam {
  key: string;
  block: string;
  blockSlug: string;
  name: string;
  docName: string;
  paramId: number;
  controlType: 'enum' | 'switch' | 'continuous';
  enumValues?: { value: number; name: string }[];
  display?: { min: number; max: number; unit: string };
  scaling?: 'linear' | 'pending';
  scalingPending?: boolean;
  range: { min?: number; default?: number; max?: number };
}
interface BlockTypeRec {
  block: string;
  instances: { name: string; decimal: number; hex: [number, number] }[];
}

const canon: CanonParam[] = JSON.parse(readFileSync(join(RESEARCH, 'canonical-params.json'), 'utf8'));
const blockTypes: BlockTypeRec[] = JSON.parse(readFileSync(join(RESEARCH, 'blockTypes.json'), 'utf8'));

// anchor (doc block name) -> slug, learned from the canonical params.
const slugByAnchor = new Map<string, string>();
for (const p of canon) if (!slugByAnchor.has(p.block)) slugByAnchor.set(p.block, p.blockSlug);

const s = JSON.stringify; // string literals, properly escaped

function emitParams(): string {
  const L: string[] = [];
  L.push('// GENERATED by scripts/generate-gen1-catalog.ts — DO NOT EDIT BY HAND.');
  L.push('// Axe-Fx Standard/Ultra (gen-1) parameter registry.');
  L.push('//');
  L.push('// Keyed `<blockSlug>.<name>`. Wire identity is (blockId, paramId); blockId is');
  L.push('// resolved from ./blockTypes.ts by slug+instance. Values are nibble-split on the');
  L.push('// wire (./nibble.ts). `scaling: "pending"` params have an unknown display curve —');
  L.push('// callers MUST NOT linearly convert them (pass raw wire).');
  L.push('//');
  L.push('// Source: published "Axe-FX Ultra System Exclusive Messages" doc. Decoded, not');
  L.push('// hardware-verified (community-beta).');
  L.push('');
  L.push("import type { AxeFxGen1Param } from './types.js';");
  L.push('');
  L.push('export const KNOWN_PARAMS: Readonly<Record<string, AxeFxGen1Param>> = Object.freeze({');
  for (const p of canon) {
    const parts: string[] = [];
    parts.push(`block: ${s(p.blockSlug)}`);
    parts.push(`name: ${s(p.name)}`);
    parts.push(`paramId: ${p.paramId}`);
    parts.push(`docName: ${s(p.docName)}`);
    parts.push(`controlType: ${s(p.controlType)}`);
    if (p.enumValues && p.enumValues.length) {
      const entries = p.enumValues.map((v) => `${v.value}: ${s(v.name)}`).join(', ');
      parts.push(`enumValues: { ${entries} }`);
    }
    if (p.display) {
      parts.push(`display: { min: ${p.display.min}, max: ${p.display.max}, unit: ${s(p.display.unit)} }`);
    }
    if (p.scaling) parts.push(`scaling: ${s(p.scaling)}`);
    const r = p.range;
    const rp: string[] = [];
    if (r.min !== undefined) rp.push(`min: ${r.min}`);
    if (r.default !== undefined) rp.push(`default: ${r.default}`);
    if (r.max !== undefined) rp.push(`max: ${r.max}`);
    parts.push(`range: { ${rp.join(', ')} }`);
    L.push(`  ${s(p.key)}: { ${parts.join(', ')} },`);
  }
  L.push('});');
  L.push('');
  L.push('export type AxeFxGen1ParamKey = keyof typeof KNOWN_PARAMS;');
  L.push('');
  L.push(`export const REGISTRY_STATS = Object.freeze({ params: ${canon.length}, blocks: ${slugByAnchor.size} });`);
  L.push('');
  return L.join('\n');
}

function emitBlockTypes(): string {
  const L: string[] = [];
  L.push('// GENERATED by scripts/generate-gen1-catalog.ts — DO NOT EDIT BY HAND.');
  L.push('// Axe-Fx Standard/Ultra (gen-1) block roster.');
  L.push('//');
  L.push('// Each block groups its instances (Amp 1 / Amp 2 share params, differ by blockId).');
  L.push('// blockId is the nibble-split 0b0b wire field (e.g. Amp 1 = 106).');
  L.push('');
  L.push("import type { AxeFxGen1Block } from './types.js';");
  L.push('');
  L.push('export const AXE_FX_GEN1_BLOCKS: readonly AxeFxGen1Block[] = Object.freeze([');
  for (const b of blockTypes) {
    const slug = slugByAnchor.get(b.block);
    if (!slug) continue; // block with no params (none expected, but be safe)
    const insts = b.instances
      .map((i) => `{ name: ${s(i.name)}, blockId: ${i.decimal} }`)
      .join(', ');
    L.push(`  { slug: ${s(slug)}, docName: ${s(b.block)}, instances: [${insts}] },`);
  }
  L.push(']);');
  L.push('');
  L.push('export const BLOCK_BY_SLUG: Readonly<Record<string, AxeFxGen1Block>> = Object.freeze(');
  L.push('  Object.fromEntries(AXE_FX_GEN1_BLOCKS.map((b) => [b.slug, b])),');
  L.push(');');
  L.push('');
  L.push('/** Resolve a block slug + 1-based instance to its wire blockId. */');
  L.push('export function blockIdFor(slug: string, instance = 1): number | undefined {');
  L.push('  const b = BLOCK_BY_SLUG[slug];');
  L.push('  return b?.instances[instance - 1]?.blockId;');
  L.push('}');
  L.push('');
  return L.join('\n');
}

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, 'params.ts'), emitParams());
writeFileSync(join(OUT, 'blockTypes.ts'), emitBlockTypes());

console.log(`generated params.ts (${canon.length} params) + blockTypes.ts (${blockTypes.length} blocks) -> ${OUT}`);
